# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  # - hhvm

# matrix:
#   # fast_finish: true
#   allow_failures:
#     - php: hhvm

addons:
  code_climate:
    repo_token: 216e591569710aa2dddeca4ca364a7385a6a875926057062a052466a3cc62da8

before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - phpenv config-rm xdebug.ini
  - wget https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer -O - -q | php -- --quiet
  - ls -la
  - php -d memory_limit=-1 ./composer.phar install -vvv
  # - composer install -vvv --prefer-source
  # - php /home/travis/.phpenv/shims/composer install -vvv --prefer-source
  # - phpenv config-add xdebug.ini

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter
